//
// Averages.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Averages: Codable {

    /** Mean price value for the car */
    public var price: Double?
    /** Mean msrp value for the car */
    public var msrp: Double?
    /** Mean miles value for the car */
    public var miles: Double?
    /** Average Days on Market value for the car based on all listings found in the Marketcheck database for this car */
    public var dom: Double?
    /** Average age of the car */
    public var age: Double?
    /** No of units for this car on the market */
    public var units: Double?



}

