//
// ComparisonPoint.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ComparisonPoint: Codable {

    /** Similar Vehicles Count */
    public var similarVehiclesCount: Double?
    /** Deal Indicator */
    public var dealerIndicator: String?
    /** Price for Vin */
    public var vinPrice: Double?
    /** Fair Deal Price */
    public var fairDealPrice: Double?


    public enum CodingKeys: String, CodingKey { 
        case similarVehiclesCount = "similar_vehicles_count"
        case dealerIndicator = "dealer_indicator"
        case vinPrice = "vin_price"
        case fairDealPrice = "fair_deal_price"
    }


}

