//
// CompetitorsPoint.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CompetitorsPoint: Codable {

    /** Details of current car */
    public var currentCar: CompetitorsCarDetails?
    public var similarCarModels: [CompetitorsSimilarCars]?
    public var sameCarModels: [CompetitorsSameCars]?


    public enum CodingKeys: String, CodingKey { 
        case currentCar = "current_car"
        case similarCarModels = "similar_car_models"
        case sameCarModels = "same_car_models"
    }


}

