//
// Dealer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Dealer: Codable {

    /** The unique id associated with the dealer in the Marketcheck database */
    public var _id: String?
    /** Dealer franchise id */
    public var franchiseId: String?
    /** Name of the dealer */
    public var name: String?
    /** Street of the dealer */
    public var street: String?
    /** City of the dealer */
    public var city: String?
    /** State of the dealer */
    public var state: String?
    /** Zip of the dealer */
    public var zip: String?
    /** Latutide for the dealer location */
    public var latitude: String?
    /** Longitude for the dealer location */
    public var longitude: String?
    /** Contact no of the dealer */
    public var phone: String?
    /** Car type new|used|certified */
    public var carType: String?
    /** Target url for the new cars listing */
    public var targetUrlNew: String?
    /** Target url for the used cars listing */
    public var targetUrlUsed: String?
    /** Target url for the certified cars listing */
    public var targetUrlCertified: String?
    /** Dealer type - independent, franchise, multi-brand, authorized */
    public var dealerType: String?
    /** Overall rating of the dealership on scale 1-5 */
    public var rating: Double?


    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case franchiseId = "franchise_id"
        case name
        case street
        case city
        case state
        case zip
        case latitude
        case longitude
        case phone
        case carType = "car_type"
        case targetUrlNew = "target_url_new"
        case targetUrlUsed = "target_url_used"
        case targetUrlCertified = "target_url_certified"
        case dealerType = "dealer_type"
        case rating
    }


}

