//
// DealerLandingPage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Describes the dealer landing page (SRP) HTML object */

public struct DealerLandingPage: Codable {

    /** The HTML string for the listing web page */
    public var html: String?
    /** The timestamp indicating the time when the SRP was cached */
    public var crawledAt: Double?
    /** The URL of the SRP */
    public var srpUrl: String?


    public enum CodingKeys: String, CodingKey { 
        case html
        case crawledAt = "crawled_at"
        case srpUrl = "srp_url"
    }


}

