//
// DealerReview.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DealerReview: Codable {

    /** Name of the dealer */
    public var name: String?
    /** Street of the dealer */
    public var street: String?
    /** City of the dealer */
    public var city: String?
    /** State of the dealer */
    public var state: String?
    /** Zip of the dealer */
    public var zip: String?
    /** Latutide for the dealer location */
    public var latitude: String?
    /** Longitude for the dealer location */
    public var longitude: String?
    /** Overall reviews of the dealership */
    public var overallReviews: Double?
    public var reviewComponents: [ReviewComponents]?


    public enum CodingKeys: String, CodingKey { 
        case name
        case street
        case city
        case state
        case zip
        case latitude
        case longitude
        case overallReviews = "overall_reviews"
        case reviewComponents = "review_components"
    }


}

