//
// DealersResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Dealers Response */

public struct DealersResponse: Codable {

    /** number of dealers found */
    public var numFound: Double?
    public var dealers: [Dealer]?


    public enum CodingKeys: String, CodingKey { 
        case numFound = "num_found"
        case dealers
    }


}

