//
// DealerRating.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DealerRating: Codable {

    /** Name of the dealer */
    public var name: String?
    /** Street of the dealer */
    public var street: String?
    /** City of the dealer */
    public var city: String?
    /** State of the dealer */
    public var state: String?
    /** Zip of the dealer */
    public var zip: String?
    /** Latutide for the dealer location */
    public var latitude: String?
    /** Longitude for the dealer location */
    public var longitude: String?
    /** Overall rating of the dealership on scale 1-5 */
    public var overallRating: Double?
    public var ratingComponents: [RatingComponents]?


    public enum CodingKeys: String, CodingKey { 
        case name
        case street
        case city
        case state
        case zip
        case latitude
        case longitude
        case overallRating = "overall_rating"
        case ratingComponents = "rating_components"
    }


}

