//
// DepreciationPoint.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DepreciationPoint: Codable {

    public var similarModels: [DepreciationStats]?


    public enum CodingKeys: String, CodingKey { 
        case similarModels = "similar_models"
    }


}

