//
// FacetItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FacetItem: Codable {

    /** Facet item */
    public var item: String?
    /** Facet item count */
    public var count: Double?



}

