//
// FuelEfficiency.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FuelEfficiency: Codable {

    /** City Mileage in MPG */
    public var cityMileage: String?
    /** Highway Mileage in MPG */
    public var highwayMileage: String?
    /** Combined Mileage */
    public var combinedMileage: String?
    /** Annual Miles of Car */
    public var annualMiles: Double?
    /** Monthly fuel expense */
    public var monthlyFuelExpense: Double?


    public enum CodingKeys: String, CodingKey { 
        case cityMileage = "city_mileage"
        case highwayMileage = "highway_mileage"
        case combinedMileage = "combined_mileage"
        case annualMiles = "annual_miles"
        case monthlyFuelExpense = "monthly_fuel_expense"
    }


}

