//
// HistoricalListing.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents a car history entry */

public struct HistoricalListing: Codable {

    /** Unique identifier representing a specific listing from the Marketcheck database */
    public var _id: String?
    /** Asking price for the car */
    public var price: String?
    /** MSRP for the car */
    public var msrp: String?
    /** Odometer reading / reported miles usage for the car */
    public var miles: String?
    /** Vehicle Details Page url of the specific car */
    public var vdpUrl: String?
    /** Seller name of the listing from the Marketcheck database */
    public var sellerName: String?
    /** Listing scraped at timestamp */
    public var scrapedAt: Double?
    /** Listing last seen at (most recent) timestamp */
    public var lastSeenAt: Double?
    /** Source website for the listing */
    public var source: String?
    /** City of the listing */
    public var city: String?
    /** State of the listing */
    public var state: String?
    /** Zip of the listing */
    public var zip: String?


    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case price
        case msrp
        case miles
        case vdpUrl = "vdp_url"
        case sellerName = "seller_name"
        case scrapedAt = "scraped_at"
        case lastSeenAt = "last_seen_at"
        case source
        case city
        case state
        case zip
    }


}

