//
// ListingMedia.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ListingMedia: Codable {

    /** Single photo url of the car */
    public var photoLink: String?
    /** A list of photo urls for the car */
    public var photoLinks: [String]?


    public enum CodingKeys: String, CodingKey { 
        case photoLink = "photo_link"
        case photoLinks = "photo_links"
    }


}

