//
// ListingExtraAttributes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ListingExtraAttributes: Codable {

    /** Installed Options of the car */
    public var options: [String]?
    /** List of Features available with the car */
    public var features: [String]?
    /** Seller comment for the car */
    public var sellerComment: String?


    public enum CodingKeys: String, CodingKey { 
        case options
        case features
        case sellerComment = "seller_comment"
    }


}

