//
// ListingVDP.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Describes the VDP (Vehicle Details Page) HTML object */

public struct ListingVDP: Codable {

    /** The HTML string for the listing web page */
    public var html: String?
    /** The timestamp indicating the time when the VDP was cached */
    public var crawledAt: Double?
    /** The URL of the VDP */
    public var vdpUrl: String?


    public enum CodingKeys: String, CodingKey { 
        case html
        case crawledAt = "crawled_at"
        case vdpUrl = "vdp_url"
    }


}

