//
// ListingDebugAttributes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ListingDebugAttributes: Codable {

    /** Robot id */
    public var robotId: Double?
    /** Cycle id */
    public var cycleId: Double?
    /** Scraped date and time */
    public var scrapedAt: String?
    /** Template id */
    public var templateId: Double?
    /** User id */
    public var userId: Double?
    /** Taxonomy vin */
    public var taxonomyVin: String?


    public enum CodingKeys: String, CodingKey { 
        case robotId = "robot_id"
        case cycleId = "cycle_id"
        case scrapedAt = "scraped_at"
        case templateId = "template_id"
        case userId = "user_id"
        case taxonomyVin = "taxonomy_vin"
    }


}

