//
// Listing.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents a full list of attributes available with Marketcheck for a car */

public struct Listing: Codable {

    /** Unique identifier representing a specific listing from the Marketcheck database */
    public var _id: String?
    /** Listing heading */
    public var heading: String?
    /** VIN for the car */
    public var vin: String?
    /** Stock no of the car */
    public var stockNo: String?
    /** Asking price for the car */
    public var price: String?
    /** MSRP for the car */
    public var msrp: String?
    /** Odometer reading / reported miles usage for the car */
    public var miles: String?
    /** Inventory type of car */
    public var inventoryType: String?
    /** Listing first seen at first scraped date */
    public var scrapedAtDate: Double?
    /** Listing first seen at first scraped timestamp */
    public var firstSeenAt: Double?
    /** Listing first seen at first scraped date */
    public var firstSeenAtDate: String?
    /** Vehicle Details Page url of the specific car */
    public var vdpUrl: String?
    /** Source domain of the listing */
    public var source: String?
    /** Flag indicating whether the car is Certified */
    public var isCertified: Int?
    /** Days on Market value for the car based on current and historical listings found in the Marketcheck database for this car */
    public var dom: Double?
    /** Days on Market value for the car based on current and last 6 month listings found in the Marketcheck database for this car */
    public var dom180: Double?
    /** Days on Market value for the car based on current and last 30 days listings found in the Marketcheck database for this car */
    public var domActive: Double?
    /** Seller type for the car */
    public var sellerType: String?
    /** Listing last seen at (most recent) timestamp */
    public var lastSeenAt: Double?
    /** Listing last seen at (most recent) date */
    public var lastSeenAtDate: String?
    /** Build / Specifications attributes */
    public var build: Build?
    /** Car Media Attributes - main photo link/url and photo links */
    public var media: ListingMedia?
    /** Extra attributes for the listing - options, features, seller comments etc */
    public var extra: ListingExtraAttributes?
    public var dealer: Dealer?
    /** Car location data. Included only if its a different location to the dealers location */
    public var carLocation: Location?


    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case heading
        case vin
        case stockNo = "stock_no"
        case price
        case msrp
        case miles
        case inventoryType = "inventory_type"
        case scrapedAtDate = "scraped_at_date"
        case firstSeenAt = "first_seen_at"
        case firstSeenAtDate = "first_seen_at_date"
        case vdpUrl = "vdp_url"
        case source
        case isCertified = "is_certified"
        case dom
        case dom180 = "dom_180"
        case domActive = "dom_active"
        case sellerType = "seller_type"
        case lastSeenAt = "last_seen_at"
        case lastSeenAtDate = "last_seen_at_date"
        case build
        case media
        case extra
        case dealer
        case carLocation = "car_location"
    }


}

