//
// Location.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents a location */

public struct Location: Codable {

    /** City of the listing */
    public var city: String?
    /** State of the listing */
    public var state: String?
    /** Zip of the listing */
    public var zip: String?
    /** Latitude component of the location */
    public var latitude: Double?
    /** Longitude component of the location */
    public var longitude: Double?



}

