//
// MakeModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MakeModel: Codable {

    public var make: String?
    public var model: String?



}

