//
// Mds.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Describes Market days supply results for year make model trim combination */

public struct Mds: Codable {

    /** Provides Market days supply count */
    public var mds: Double?
    /** Active cars for ymmt combination */
    public var totalActiveCarsForYmmt: Double?
    /** Cars sold in last 45 days */
    public var totalCarsSoldInLast45Days: Double?


    public enum CodingKeys: String, CodingKey { 
        case mds
        case totalActiveCarsForYmmt = "total_active_cars_for_ymmt"
        case totalCarsSoldInLast45Days = "total_cars_sold_in_last_45_days"
    }


}

