//
// ModelError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ModelError: Codable {

    /** Error code */
    public var status: Double?
    /** Error message */
    public var message: String?



}

