//
// RatingComponents.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RatingComponents: Codable {

    /** Specifices rating condition parameter */
    public var ratingCondition: String?
    /** rating of car on that condition */
    public var actualRating: Double?


    public enum CodingKeys: String, CodingKey { 
        case ratingCondition = "rating_condition"
        case actualRating = "actual_rating"
    }


}

