//
// ReviewComponents.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReviewComponents: Codable {

    /** Name of user who has given review */
    public var userName: String?
    /** rating for dealer given by user ranging from 1-5 */
    public var userRating: Double?
    /** review of car given by current user */
    public var actualReview: String?


    public enum CodingKeys: String, CodingKey { 
        case userName = "user_name"
        case userRating = "user_rating"
        case actualReview = "actual_review"
    }


}

