//
// SafetyRating.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Describes the Safety Ratings of current listing */

public struct SafetyRating: Codable {

    /** Overall rating of the Listing on scale 1-5 */
    public var overallRating: Double?
    /** Roll Over rating of the Listing on scale 1-5 */
    public var rollOverRating: Double?
    /** Driver Side rating of the Listing on scale 1-5 */
    public var driverSideRating: Double?
    /** Driver front rating of the Listing on scale 1-5 */
    public var driverFrontRating: Double?
    /** Passenger front rating of the Listing on scale 1-5 */
    public var passengerFrontRating: Double?


    public enum CodingKeys: String, CodingKey { 
        case overallRating = "overall_rating"
        case rollOverRating = "roll_over_rating"
        case driverSideRating = "driver_side_rating"
        case driverFrontRating = "driver_front_rating"
        case passengerFrontRating = "passenger_front_rating"
    }


}

