//
// SearchResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Search query response */

public struct SearchResponse: Codable {

    /** The number of listings found */
    public var numFound: Double?
    public var listings: [BaseListing]?


    public enum CodingKeys: String, CodingKey { 
        case numFound = "num_found"
        case listings
    }


}

