//
// TrendPoint.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TrendPoint: Codable {

    /** Price */
    public var price: Double?
    /** Miles */
    public var miles: Double?
    /** Days on Market */
    public var dom: Double?
    /** Units */
    public var units: Double?
    /** MSRP */
    public var msrp: Double?



}

