//
// VinReport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VinReport: Codable {

    /** icon url */
    public var icon: String?
    /** Some descriptional text */
    public var someText: String?


    public enum CodingKeys: String, CodingKey { 
        case icon
        case someText = "some_text"
    }


}

