//
// FacetsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class FacetsAPI {
    /**
     Facets
     
     - parameter fields: (query) Comma separated list of fields to generate facets for. Supported fields are - year, make, model, trim, exterior_color, interior_color, drivetrain, vehicle_type, car_type, body_style, body_subtype, doors 
     - parameter apiKey: (query) The API Authentication Key. Mandatory with all API calls. (optional)
     - parameter vin: (query) VIN as a reference to the type of car for which facets data is to be returned (optional)
     - parameter year: (query) Year of the car (optional)
     - parameter make: (query) Make of the car (optional)
     - parameter model: (query) Model of the Car (optional)
     - parameter trim: (query) Trim of the Car (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getFacets(fields: String, apiKey: String? = nil, vin: String? = nil, year: String? = nil, make: String? = nil, model: String? = nil, trim: String? = nil, completion: @escaping ((_ data: [FacetItem]?,_ error: Error?) -> Void)) {
        getFacetsWithRequestBuilder(fields: fields, apiKey: apiKey, vin: vin, year: year, make: make, model: model, trim: trim).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Facets
     - GET /facets
     - [Merged with the /search API - Please check the 'facets' parameter to the Search API above] Get the facets for the given simple filter criteria (by given VIN's basic specification, Or by Year, Make, Model, Trim criteria) and facet fields
     - examples: [{contentType=application/json, example=[ {
  "item" : "item",
  "count" : 0.80082819046101150206595775671303272247314453125
}, {
  "item" : "item",
  "count" : 0.80082819046101150206595775671303272247314453125
} ]}]
     
     - parameter fields: (query) Comma separated list of fields to generate facets for. Supported fields are - year, make, model, trim, exterior_color, interior_color, drivetrain, vehicle_type, car_type, body_style, body_subtype, doors 
     - parameter apiKey: (query) The API Authentication Key. Mandatory with all API calls. (optional)
     - parameter vin: (query) VIN as a reference to the type of car for which facets data is to be returned (optional)
     - parameter year: (query) Year of the car (optional)
     - parameter make: (query) Make of the car (optional)
     - parameter model: (query) Model of the Car (optional)
     - parameter trim: (query) Trim of the Car (optional)

     - returns: RequestBuilder<[FacetItem]> 
     */
    open class func getFacetsWithRequestBuilder(fields: String, apiKey: String? = nil, vin: String? = nil, year: String? = nil, make: String? = nil, model: String? = nil, trim: String? = nil) -> RequestBuilder<[FacetItem]> {
        let path = "/facets"
        let URLString = MarketcheckCarsApiAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "api_key": apiKey, 
            "vin": vin, 
            "year": year, 
            "make": make, 
            "model": model, 
            "trim": trim, 
            "fields": fields
        ])
        

        let requestBuilder: RequestBuilder<[FacetItem]>.Type = MarketcheckCarsApiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
