//
// HistoryAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class HistoryAPI {
    /**
     Get a cars online listing history
     
     - parameter vin: (path) The VIN to identify the car to fetch the listing history. Must be a valid 17 char VIN 
     - parameter apiKey: (query) The API Authentication Key. Mandatory with all API calls. (optional)
     - parameter fields: (query) List of fields to fetch, in case the default fields list in the response is to be trimmed down (optional)
     - parameter rows: (query) Number of results to return. Default is 10. Max is 50 (optional)
     - parameter page: (query) Page number to fetch the results for the given criteria. Default is 1. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func history(vin: String, apiKey: String? = nil, fields: String? = nil, rows: Int? = nil, page: Double? = nil, completion: @escaping ((_ data: [HistoricalListing]?,_ error: Error?) -> Void)) {
        historyWithRequestBuilder(vin: vin, apiKey: apiKey, fields: fields, rows: rows, page: page).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get a cars online listing history
     - GET /history/{vin}
     - The history API returns online listing history for a car identified by its VIN. History listings are sorted in the descending order of the listing date / last seen date
     - examples: [{contentType=application/json, example=[ {
  "zip" : "zip",
  "seller_name" : "seller_name",
  "city" : "city",
  "price" : "price",
  "scraped_at" : 0.80082819046101150206595775671303272247314453125,
  "msrp" : "msrp",
  "vdp_url" : "vdp_url",
  "id" : "id",
  "source" : "source",
  "state" : "state",
  "last_seen_at" : 6.02745618307040320615897144307382404804229736328125,
  "miles" : "miles"
}, {
  "zip" : "zip",
  "seller_name" : "seller_name",
  "city" : "city",
  "price" : "price",
  "scraped_at" : 0.80082819046101150206595775671303272247314453125,
  "msrp" : "msrp",
  "vdp_url" : "vdp_url",
  "id" : "id",
  "source" : "source",
  "state" : "state",
  "last_seen_at" : 6.02745618307040320615897144307382404804229736328125,
  "miles" : "miles"
} ]}]
     
     - parameter vin: (path) The VIN to identify the car to fetch the listing history. Must be a valid 17 char VIN 
     - parameter apiKey: (query) The API Authentication Key. Mandatory with all API calls. (optional)
     - parameter fields: (query) List of fields to fetch, in case the default fields list in the response is to be trimmed down (optional)
     - parameter rows: (query) Number of results to return. Default is 10. Max is 50 (optional)
     - parameter page: (query) Page number to fetch the results for the given criteria. Default is 1. (optional)

     - returns: RequestBuilder<[HistoricalListing]> 
     */
    open class func historyWithRequestBuilder(vin: String, apiKey: String? = nil, fields: String? = nil, rows: Int? = nil, page: Double? = nil) -> RequestBuilder<[HistoricalListing]> {
        var path = "/history/{vin}"
        let vinPreEscape = "\(vin)"
        let vinPostEscape = vinPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{vin}", with: vinPostEscape, options: .literal, range: nil)
        let URLString = MarketcheckCarsApiAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "api_key": apiKey, 
            "fields": fields, 
            "rows": rows?.encodeToJSON(), 
            "page": page
        ])
        

        let requestBuilder: RequestBuilder<[HistoricalListing]>.Type = MarketcheckCarsApiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
